models:
  deepseek/chat:
    provider: deepseek
    provider_model_name: deepseek-chat
  deepseek/reasoner:
    provider: deepseek
    provider_model_name: deepseek-reasoner
  kimi/chat:
    provider: kimi
    provider_model_name: kimi-k2-0905-preview
  glm/air:
    provider: openrouter
    provider_model_name: z-ai/glm-4.5-air
    options:
      provider:
        only: ["z-ai"]
  glm/chat:
    provider: openrouter
    provider_model_name: z-ai/glm-4.6
    options:
      provider:
        only: ["z-ai"]
  anthropic/sonnet:
    provider: openrouter
    provider_model_name: anthropic/claude-sonnet-4.5
  gemini/mini:
    provider: openrouter
    provider_model_name: google/gemini-2.0-flash-001
  gemini/chat:
    provider: openrouter
    provider_model_name: google/gemini-2.5-flash
  gemini/pro:
    provider: openrouter
    provider_model_name: google/gemini-2.5-pro
  mistral/dev/medium:
    provider: openrouter
    provider_model_name: mistralai/devstral-medium
    options:
      provider:
        only: ["mistral"]
  minimax/reasoner:
    provider: openrouter
    provider_model_name: minimax/minimax-m1
    options:
      provider:
        only: ["minimax"]
  local/orange:
    provider: orange
    provider_model_name: dummy
  local/box:
    provider: box
    provider_model_name: dummy
  embeddings/dummy:
    provider: embedding
    provider_model_name: dummy
    is_hidden: true
  stt/dummy:
    provider: transcriber
    provider_model_name: dummy
    is_hidden: true
#  ollama/gemma3n:
#    provider: ollama
#    provider_model_name: gemma3n
