models:
  deepseek/chat:
    provider: deepseek
    provider_model_name: deepseek-chat
  deepseek/reasoner:
    provider: deepseek
    provider_model_name: deepseek-reasoner
  anthropic/sonnet:
    provider: openrouter
    provider_model_name: anthropic/claude-sonnet-4
  gemini/mini:
    provider: openrouter
    provider_model_name: google/gemini-2.0-flash-001
  gemini/chat:
    provider: openrouter
    provider_model_name: google/gemini-2.5-flash-preview-05-20
  gemini/pro:
    provider: openrouter
    provider_model_name: google/gemini-2.5-pro
  mistral/mistral-small:
    provider: openrouter
    provider_model_name: mistralai/mistral-small-3.2-24b-instruct
    options:
      provider:
        only: ["mistral"]
  mistral/devstral-small:
    provider: openrouter
    provider_model_name: mistralai/devstral-small
    options:
      provider:
        only: ["mistral"]
  minimax/reasoner:
    provider: openrouter
    provider_model_name: minimax/minimax-m1
    options:
      provider:
        only: ["minimax"]
  local/orange/small:
    provider: orange
    provider_model_name: dummy
  local/box/small:
    provider: box
    provider_model_name: dummy
  embeddings/dummy:
    provider: orange
    provider_model_name: dummy
  transcriptions/dummy:
    provider: transcriptions
    provider_model_name: dummy
