models:
  deepseek/chat:
    provider: deepseek
    provider_model_name: deepseek-chat
  gemini/mini:
    provider: openrouter
    provider_model_name: google/gemini-2.0-flash-001
  local/orange:
    provider: orange
    provider_model_name: dummy
    options:
      chat_template_kwargs:
        enable_thinking: false
  embeddings/dummy:
    provider: embedding
    provider_model_name: dummy
    is_hidden: true
  stt/dummy:
    provider: transcriber
    provider_model_name: dummy
    is_hidden: true
