providers:
  openai:
    type: openai
    base_url: https://api.openai.com/v1
    api_key_env: OPENAI_API_KEY
  deepseek:
    type: openai # DeepSeek совместим с OpenAI API
    base_url: https://api.deepseek.com/v1
    api_key_env: DEEPSEEK_API_KEY
  openrouter:
    type: openai # OpenRouter совместим с OpenAI API
    base_url: https://openrouter.ai/api/v1
    api_key_env: OPENROUTER_API_KEY
    headers:
      HTTP-Referer: "https://nnp.space"
      X-Title: "nnp.space"
  orange:  # Локальный сервер ORANGE
    type: openai
    base_url: http://192.168.1.52:5010/v1
    api_key_env: ORANGE_API_KEY
  transcriptions:
    type: openai
    base_url: http://192.168.1.52:5042/v1
    api_key_env: TRANSCRIPTIONS_API_KEY
