user_keys:
  debug:
    api_key: dummy
    allowed_models:  # Доступ ко всем моделям. Пустой или не указывать
    allowed_endpoints: # Доступ ко всем эндпоинтам. Пустой или не указывать
  limited:
    api_key: limited
    allowed_models:
      - local/orange
  transctiber:
    api_key: transctiber
    allowed_models:
    allowed_endpoints:
      - /v1/audio/transcriptions
      - /v1/models
