"""Typed request context carried through the request lifecycle.

Replaces raw string keys on request.state (request_id, project_name) with a
single typed attribute. Frozen + rebuilt so auth can attach project_name
without mutating the middleware-created instance.
"""
from dataclasses import dataclass, replace
from typing import Optional


@dataclass(frozen=True)
class RequestContext:
    """Immutable per-request context.

    request_id: generated by middleware (always present).
    project_name: resolved by auth from the API key (None until authenticated).
    """
    request_id: str
    project_name: Optional[str] = None

    @property
    def user_id(self) -> str:
        """user_id for logging/auth metadata; 'unknown' until authenticated."""
        return self.project_name or "unknown"

    def with_project_name(self, project_name: str) -> "RequestContext":
        """Return a copy with project_name set."""
        return replace(self, project_name=project_name)

