"""Typed request context carried through the request lifecycle.

Replaces raw string keys on request.state (request_id, project_name) with a
single typed attribute. Frozen + rebuilt so auth can attach project_name
without mutating the middleware-created instance.
"""
# SYSTEM: request-context — the typed RequestContext carried per request
from dataclasses import dataclass, replace


@dataclass(frozen=True)
class RequestContext:
    """Immutable per-request context.

    request_id: generated by middleware (always present).
    project_name: resolved by auth from the API key (None until authenticated).
    """
    request_id: str
    project_name: str | None = None

    @property
    def user_id(self) -> str:
        """user_id for logging/auth metadata; 'unknown' until authenticated."""
        return self.project_name or "unknown"

    def with_project_name(self, project_name: str) -> "RequestContext":
        """Return a copy with project_name set."""
        return replace(self, project_name=project_name)


# INVARIANT: the single auth contract crossing auth → services.
# Why: the positional 4-tuple it replaced forced every consumer to unpack by
# position, and its second element (the raw api_key) was read nowhere in src/
# — a credential slot with no consumer. project_name stays here even though
# RequestContext also carries it: the endpoint checker logs it before
# RequestContext is rebuilt; one owner per contract is a separate task.
@dataclass(frozen=True)
class AuthContext:
    """Resolved identity and grants of an authenticated API key.

    Built once per request by auth.get_api_key; carried into services and
    endpoint dependencies. Fields are read by name — adding one is a typed
    change, not a new positional slot every unpack site must survive.
    """
    project_name: str
    allowed_models: list[str]
    allowed_endpoints: list[str]


# INVARIANT: the single way to read the context off a request. Routes and
# services used to each carry their own accessor (one returning the dataclass,
# one a plain dict), which is how the typed context leaked back into strings.
_UNKNOWN = RequestContext(request_id="unknown")


def request_context(request: object | None) -> RequestContext:
    """Read the RequestContext set by middleware, or an 'unknown' placeholder.

    Tolerates a missing request and a request that never passed through the
    middleware (unit tests, ASGI lifespan), so callers never branch on it.
    """
    if request is None:
        return _UNKNOWN
    ctx = getattr(getattr(request, "state", None), "request_context", None)
    return ctx if isinstance(ctx, RequestContext) else _UNKNOWN

