"""Typed request context carried through the request lifecycle.

Replaces raw string keys on request.state (request_id, project_name) with a
single typed attribute. Frozen + rebuilt so auth can attach project_name
without mutating the middleware-created instance.
"""
# SYSTEM: request-context — the typed RequestContext carried per request
from dataclasses import dataclass, replace
from typing import Optional


@dataclass(frozen=True)
class RequestContext:
    """Immutable per-request context.

    request_id: generated by middleware (always present).
    project_name: resolved by auth from the API key (None until authenticated).
    """
    request_id: str
    project_name: Optional[str] = None

    @property
    def user_id(self) -> str:
        """user_id for logging/auth metadata; 'unknown' until authenticated."""
        return self.project_name or "unknown"

    def with_project_name(self, project_name: str) -> "RequestContext":
        """Return a copy with project_name set."""
        return replace(self, project_name=project_name)


# INVARIANT: the single way to read the context off a request. Routes and
# services used to each carry their own accessor (one returning the dataclass,
# one a plain dict), which is how the typed context leaked back into strings.
_UNKNOWN = RequestContext(request_id="unknown")


def request_context(request: Optional[object]) -> RequestContext:
    """Read the RequestContext set by middleware, or an 'unknown' placeholder.

    Tolerates a missing request and a request that never passed through the
    middleware (unit tests, ASGI lifespan), so callers never branch on it.
    """
    if request is None:
        return _UNKNOWN
    ctx = getattr(getattr(request, "state", None), "request_context", None)
    return ctx if isinstance(ctx, RequestContext) else _UNKNOWN

