#!/usr/bin/env python3
"""Print a config/model_info.yaml draft from the model capabilities auto-cache.

The auto-cache (``data/model_cache.json``, filled by the background refresh
task) stores the SAME normalized schema as the manual layer, so a draft is a
straight re-print of the cached entries — there is no second normalizer to keep
in sync and no network call.

It NEVER edits config and is NEVER imported by the app. It prints YAML to stdout
for manual review / pasting into config/model_info.yaml. Paste only the fields
an operator wants to PIN: whatever stays out of model_info.yaml keeps tracking
upstream through the cache.

Run (standalone CLI):

    python scripts/dump_model_info.py
    python scripts/dump_model_info.py --path /app/data/model_cache.json
    python scripts/dump_model_info.py deepseek/flash gemini/mini

    # inside the container, where the cache volume actually lives:
    docker compose exec api python scripts/dump_model_info.py
"""
import argparse
import json
import sys
from datetime import UTC, datetime
from typing import Any

import yaml


def load_entries(path: str, wanted: list[str]) -> dict[str, dict[str, Any]]:
    """Read the cache file and return the {model_id: record} entries selected by ``wanted``."""
    with open(path) as f:
        raw = json.load(f)
    if not isinstance(raw, dict):
        raise ValueError(f"{path}: expected a JSON object at the top level")
    selected = wanted or sorted(raw)
    missing = [m for m in selected if m not in raw]
    if missing:
        raise KeyError(f"not in the cache: {', '.join(missing)}")
    return {model_id: raw[model_id] for model_id in selected}


def render_draft(entries: dict[str, dict[str, Any]], path: str) -> str:
    """Render the model_info.yaml draft, one commented block per model."""
    lines = [
        "# Draft generated by scripts/dump_model_info.py — REVIEW BEFORE PASTING.",
        f"# Source: {path}",
        "# Only pin the fields you want frozen; the rest keeps tracking upstream.",
        "model_info:",
    ]
    for model_id, record in entries.items():
        data = record.get("data") if isinstance(record, dict) else None
        fetched_at = record.get("fetched_at") if isinstance(record, dict) else None
        source = record.get("source") if isinstance(record, dict) else None
        stamp = (
            datetime.fromtimestamp(fetched_at, UTC).isoformat(timespec="seconds")
            if isinstance(fetched_at, (int, float)) else "unknown"
        )
        lines.append(f"  # source: {source or 'unknown'} · fetched_at: {stamp}")
        if not data:
            lines.append(f"  # {model_id}: no capabilities cached (upstream returned nothing)")
            continue
        body = yaml.safe_dump({model_id: data}, sort_keys=False, allow_unicode=True,
                              default_flow_style=False, width=100)
        lines.extend("  " + line for line in body.rstrip("\n").split("\n"))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("models", nargs="*", help="model ids to dump (default: all cached)")
    parser.add_argument("--path", default="data/model_cache.json", help="cache file path")
    args = parser.parse_args()
    try:
        entries = load_entries(args.path, args.models)
    except (OSError, ValueError, KeyError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if not entries:
        print(f"error: {args.path} holds no cached models", file=sys.stderr)
        return 1
    sys.stdout.write(render_draft(entries, args.path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
